INSTALLDIRECTORY='/gpfs/home/jac15r/usr'

export LD_LIBRARY_PATH=$INSTALLDIRECTORY/lib
export LIBRARY_PATH=$INSTALLDIRECTORY/lib
export C_INCLUDE_PATH=$INSTALLDIRECTORY/include
export CPLUS_INCLUDE_PATH=$INSTALLDIRECTORY/include
